spring:
  application:
    name: component-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AtulDwivedi/quickcart-configuration
          searchPaths: application

server:
  port: 8081

