spring:
  application:
    name: component-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/routinecart/routinecart-configuration
          searchPaths: application

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh

